[package]
name = "sway-dynamic-ws"
version = "0.1.0"
authors = ["Antoine Eiche <lewo@abesis.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i3ipc = "0.10.1"
clap = "2.31.2"
